/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Villa(props) {
  const { nodes, materials } = useGLTF("/assets/3d/Villa_3.gltf", true);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.010"]}
        position={[0, 2.16, 0]}
        scale={2.19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[5.92, 2.79, 1.12]}
        scale={[0.18, 0.62, 0.37]}
      />
      {/*<mesh*/}
      {/*  castShadow*/}
      {/*  receiveShadow*/}
      {/*  geometry={nodes.Cube002.geometry}*/}
      {/*  material={nodes.Cube002.material}*/}
      {/*  position={[-0.57, 2.41, 2.84]}*/}
      {/*  scale={[2.31, 1, 1]}*/}
      {/*/>*/}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.010"]}
        position={[-0.21, 4.64, 0.98]}
        scale={[1.96, 1, 3.17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[1.75, 4.64, 0.98]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.2, -0.7, -2.85]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Material.007"]}
        position={[-1.4, 5.28, 4.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.45, 0.06, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials["Material.008"]}
        position={[0.39, 4.64, 4.07]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.35, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.008"]}
        position={[1.7, 4.64, 2.77]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.35, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.007"]}
        position={[1.72, 5.28, 1.55]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.87, 0.06, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["Material.008"]}
        position={[1.69, 4.64, -0.16]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.71, 0.71, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Material.007"]}
        position={[1.72, 5.28, -1.42]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.46, 0.06, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-0.35, 5.64, 0.22]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.16, -2.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Material.008"]}
        position={[-0.35, 5.33, 0.22]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.16, -2.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials["Material.007"]}
        position={[5.08, 2.79, 1.93]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.007"]}
        position={[4.11, 2.79, 1.93]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials["Material.007"]}
        position={[3.15, 2.79, 1.93]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials["Material.007"]}
        position={[2.18, 2.79, 1.93]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["Material.007"]}
        position={[1.22, 2.79, 1.93]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane045.geometry}
        material={materials["Material.007"]}
        position={[0.25, 2.79, 1.93]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[4.18, 3.94, -0.15]}
        scale={[1.6, 1.26, 1.87]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.018"]}
        position={[2.12, 4.21, 2.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.33, 0.24, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials["Material.018"]}
        position={[5.92, 4.21, 1.73]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.33, 0.24, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials["Material.018"]}
        position={[2.12, 4.21, -2.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.33, 0.24, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials["Material.008"]}
        position={[1.83, 3.94, 2.08]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials["Material.008"]}
        position={[5.89, 3.94, 2.08]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={materials["Material.008"]}
        position={[5.89, 3.94, -2.09]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials["Material.008"]}
        position={[1.87, 3.94, -2.09]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere010.geometry}
        material={materials["Material.008"]}
        position={[8, 2.21, -2.11]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere011.geometry}
        material={materials["Material.008"]}
        position={[8.01, 2.21, -0.16]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere012.geometry}
        material={materials["Material.008"]}
        position={[8.01, 2.21, 3.1]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere013.geometry}
        material={materials["Material.008"]}
        position={[8.01, 2.21, 6.4]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere014.geometry}
        material={materials["Material.008"]}
        position={[6.65, 2.21, 8.35]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere015.geometry}
        material={materials["Material.008"]}
        position={[3.28, 2.21, 8.35]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere016.geometry}
        material={materials["Material.008"]}
        position={[-0.12, 2.21, 8.35]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere017.geometry}
        material={materials["Material.008"]}
        position={[-2.13, 2.21, 7.05]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere018.geometry}
        material={materials["Material.008"]}
        position={[-2.13, 2.21, 4.46]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere019.geometry}
        material={materials["Material.008"]}
        position={[-2.13, 2.21, 1.89]}
        scale={0.06}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials["Material.012"]}
        position={[5.47, 5.16, -1.67]}
        scale={0.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials["Material.013"]}
        position={[5.47, 5.99, -1.67]}
        rotation={[-0.09, 0.01, -0.02]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials["Material.013"]}
        position={[5.47, 5.99, -1.67]}
        rotation={[-0.37, -1.21, -0.4]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials["Material.013"]}
        position={[5.47, 5.99, -1.67]}
        rotation={[-2.92, -0.47, -3.12]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={materials["Material.013"]}
        position={[5.47, 5.99, -1.67]}
        rotation={[-2.9, 0.78, 2.94]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={materials["Material.013"]}
        position={[5.47, 5.99, -1.67]}
        rotation={[-0.26, 1.18, 0.18]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials["Material.013"]}
        position={[5.47, 6.04, -1.67]}
        rotation={[-0.05, -0.54, -0.09]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials["Material.013"]}
        position={[5.47, 6.04, -1.67]}
        rotation={[-2.91, -1.35, -3.02]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials["Material.013"]}
        position={[5.47, 6.04, -1.67]}
        rotation={[-3.08, 0.08, 3.04]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials["Material.013"]}
        position={[5.47, 6.04, -1.67]}
        rotation={[-2.82, 1.34, 2.87]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials["Material.013"]}
        position={[5.47, 6.04, -1.67]}
        rotation={[-0.02, 0.62, -0.03]}
        scale={[0.2, 0.57, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004.geometry}
        material={materials["Material.014"]}
        position={[1.16, 5.5, -1.8]}
        scale={0.09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={materials["Material.014"]}
        position={[1.16, 5.5, 0.47]}
        scale={0.09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere006.geometry}
        material={materials["Material.014"]}
        position={[1.16, 5.5, 3.62]}
        scale={0.09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere007.geometry}
        material={materials["Material.014"]}
        position={[-1.97, 5.5, 3.62]}
        scale={0.09}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials["Material.010"]}
        position={[3.03, 2.17, 5.3]}
        scale={[5.87, 7.49, 7.49]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials["Material.018"]}
        position={[8.01, 2.44, -1.8]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.31, 0.24, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials["Material.018"]}
        position={[-1.79, 2.44, 8.36]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.24, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials["Material.018"]}
        position={[-2.14, 2.44, 2.17]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.31, 0.24, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials["Material.018"]}
        position={[6.32, 2.44, -2.11]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.24, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials["Material.004"]}
        position={[3.89, 2.79, 3.26]}
        scale={[0.77, 0.52, 0.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials["Material.004"]}
        position={[4.49, 2.75, 3]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials["Material.011"]}
        position={[5.1, 2.78, 3.28]}
        rotation={[Math.PI / 2, 0, 1.58]}
        scale={0.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={materials["Material.011"]}
        position={[4.39, 2.78, 4.01]}
        rotation={[Math.PI / 2, 0, 2.96]}
        scale={0.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008.geometry}
        material={materials["Material.011"]}
        position={[3.61, 2.78, 4.05]}
        rotation={[Math.PI / 2, 0, -3.05]}
        scale={0.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle011.geometry}
        material={materials["Material.011"]}
        position={[2.76, 2.78, 3.35]}
        rotation={[Math.PI / 2, 0, -1.43]}
        scale={0.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials["Material.008"]}
        position={[5.21, 2.91, 3.28]}
        rotation={[1.57, -0.1, 1.58]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004.geometry}
        material={materials["Material.008"]}
        position={[5, 2.5, 3.28]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={0.2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={materials["Material.008"]}
        position={[4.42, 2.91, 4.13]}
        rotation={[1.67, -0.02, 2.96]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={materials["Material.008"]}
        position={[4.37, 2.5, 3.92]}
        rotation={[Math.PI, -0.18, Math.PI]}
        scale={0.2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle009.geometry}
        material={materials["Material.008"]}
        position={[3.6, 2.91, 4.16]}
        rotation={[1.67, 0.01, -3.05]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle010.geometry}
        material={materials["Material.008"]}
        position={[3.61, 2.5, 3.95]}
        rotation={[-Math.PI, 0.09, -Math.PI]}
        scale={0.2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle012.geometry}
        material={materials["Material.008"]}
        position={[2.64, 2.91, 3.34]}
        rotation={[1.56, 0.1, -1.43]}
        scale={0.16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle013.geometry}
        material={materials["Material.008"]}
        position={[2.85, 2.5, 3.36]}
        rotation={[0, 1.43, 0]}
        scale={0.2}
      />
      {/*<mesh*/}
      {/*  castShadow*/}
      {/*  receiveShadow*/}
      {/*  geometry={nodes.Cube001.geometry}*/}
      {/*  material={nodes.Cube001.material}*/}
      {/*  position={[5.41, 2.17, 6.64]}*/}
      {/*  scale={[1.92, 0.89, 1.22]}*/}
      {/*/>*/}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Material.002"]}
        position={[5.41, 1.72, 6.64]}
        scale={[1.92, 0.24, 1.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane035.geometry}
        material={materials["Material.006"]}
        position={[0.12, 2.21, 5.44]}
        scale={[1.99, 0.06, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane036.geometry}
        material={materials["Material.004"]}
        position={[0.89, 1.96, 7.59]}
        scale={[0.92, 0.92, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane037.geometry}
        material={materials["Material.004"]}
        position={[0.89, 1.96, 6.17]}
        scale={[0.92, 0.92, 0.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle014.geometry}
        material={materials["Material.005"]}
        position={[1.53, 2.36, 7.32]}
        scale={-0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle015.geometry}
        material={materials["Material.005"]}
        position={[1.53, 2.36, 7.85]}
        scale={-0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle016.geometry}
        material={materials["Material.005"]}
        position={[0.12, 2.36, 7.85]}
        scale={-0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle017.geometry}
        material={materials["Material.005"]}
        position={[0.12, 2.36, 7.31]}
        scale={-0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle018.geometry}
        material={materials["Material.005"]}
        position={[1.53, 2.36, 5.91]}
        scale={-0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle019.geometry}
        material={materials["Material.005"]}
        position={[1.53, 2.36, 6.43]}
        scale={-0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle020.geometry}
        material={materials["Material.005"]}
        position={[0.12, 2.36, 6.43]}
        scale={-0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle021.geometry}
        material={materials["Material.005"]}
        position={[0.12, 2.36, 5.9]}
        scale={-0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={materials["Material.008"]}
        position={[5.85, 2.95, 1.12]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.46, 0.26, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane039.geometry}
        material={materials["Material.003"]}
        position={[0.39, 4.64, 4.07]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.35, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={materials["Material.003"]}
        position={[1.7, 4.64, 2.77]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1.35, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane041.geometry}
        material={materials["Material.009"]}
        position={[1.69, 4.64, -0.16]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.71, 0.71, 0.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane042.geometry}
        material={materials["Material.009"]}
        position={[5.85, 2.95, 1.12]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.46, 0.26, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane043.geometry}
        material={materials["Material.009"]}
        position={[5.08, 2.79, 2.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials["Material.009"]}
        position={[4.11, 2.79, 2.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials["Material.009"]}
        position={[3.15, 2.79, 2.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials["Material.009"]}
        position={[2.18, 2.79, 2.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane044.geometry}
        material={materials["Material.009"]}
        position={[1.22, 2.79, 2.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane046.geometry}
        material={materials["Material.009"]}
        position={[0.25, 2.79, 2.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.48, 0.57, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle027.geometry}
        material={materials["Material.019"]}
        position={[-0.63, 2.63, 3.89]}
        rotation={[-1.57, -1.55, -1.57]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle026.geometry}
        material={materials["Material.020"]}
        position={[-0.63, 2.63, 3.89]}
        rotation={[-1.57, -1.55, -1.57]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle025.geometry}
        material={materials["Material.024"]}
        position={[-0.63, 2.63, 3.89]}
        rotation={[-1.57, -1.55, -1.57]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle024.geometry}
        material={materials["Material.019"]}
        position={[-0.63, 2.63, 4.04]}
        rotation={[-0.02, -0.85, 3.1]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle023.geometry}
        material={materials["Material.020"]}
        position={[-0.63, 2.63, 4.04]}
        rotation={[-0.02, -0.85, 3.1]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle022.geometry}
        material={materials["Material.024"]}
        position={[-0.63, 2.64, 4.04]}
        rotation={[-0.02, -0.85, 3.1]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.021"]}
        position={[-0.91, 2.61, 4.3]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.022"]}
        position={[0.18, 2.61, 4.3]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.021"]}
        position={[-0.91, 2.61, 2.95]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.021"]}
        position={[0.18, 2.61, 2.95]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.021"]}
        position={[-0.68, 2.6, 4.3]}
        rotation={[-Math.PI / 2, -0.71, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials["Material.024"]}
        position={[-0.91, 2.61, 4.3]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials["Material.024"]}
        position={[-0.91, 2.61, 2.95]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials["Material.024"]}
        position={[0.18, 2.61, 2.95]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials["Material.024"]}
        position={[0.18, 2.61, 4.3]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials["Material.021"]}
        position={[-0.02, 2.64, 4.3]}
        rotation={[Math.PI / 2, -0.77, Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials["Material.021"]}
        position={[-0.68, 2.6, 2.95]}
        rotation={[-Math.PI / 2, -0.71, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials["Material.021"]}
        position={[-0.02, 2.64, 2.95]}
        rotation={[Math.PI / 2, -0.77, Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials["Material.021"]}
        position={[0.26, 2.61, 4.3]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials["Material.021"]}
        position={[1.35, 2.61, 4.3]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials["Material.021"]}
        position={[0.26, 2.61, 2.95]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials["Material.021"]}
        position={[1.35, 2.61, 2.95]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials["Material.021"]}
        position={[0.49, 2.6, 4.3]}
        rotation={[-Math.PI / 2, -0.71, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials["Material.024"]}
        position={[0.26, 2.61, 4.3]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials["Material.024"]}
        position={[0.26, 2.61, 2.95]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials["Material.024"]}
        position={[1.35, 2.61, 2.95]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials["Material.024"]}
        position={[1.35, 2.61, 4.3]}
        rotation={[0, -1.57, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder021.geometry}
        material={materials["Material.021"]}
        position={[1.15, 2.64, 4.3]}
        rotation={[Math.PI / 2, -0.77, Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder022.geometry}
        material={materials["Material.021"]}
        position={[0.49, 2.6, 2.95]}
        rotation={[-Math.PI / 2, -0.71, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials["Material.021"]}
        position={[1.15, 2.64, 2.95]}
        rotation={[Math.PI / 2, -0.77, Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials["Material.022"]}
        position={[0.23, 2.66, 4.35]}
        rotation={[0, -1.57, 0]}
        scale={[0, 0.07, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane071.geometry}
        material={nodes.Plane071.material}
        position={[0.23, 2.68, 3.62]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.73, 0.29, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane069.geometry}
        material={nodes.Plane069.material}
        position={[0.81, 2.63, 3.62]}
        rotation={[0, -1.57, 0]}
        scale={[0.73, 0.6, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane067.geometry}
        material={materials["Material.023"]}
        position={[-0.36, 2.63, 3.62]}
        rotation={[0, -1.57, 0]}
        scale={[0.73, 0.6, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane066.geometry}
        material={materials["Material.020"]}
        position={[-0.66, 2.58, 3.9]}
        rotation={[-1.57, -1.55, -1.57]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane065.geometry}
        material={materials["Material.024"]}
        position={[0.23, 2.68, 3.62]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.73, 0.29, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane064.geometry}
        material={materials["Material.024"]}
        position={[0.23, 2.68, 3.62]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.73, 0.29, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane063.geometry}
        material={materials["Material.022"]}
        position={[-0.36, 2.63, 3.62]}
        rotation={[0, -1.57, 0]}
        scale={[0.73, 0.6, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane062.geometry}
        material={materials["Material.022"]}
        position={[0.81, 2.63, 3.62]}
        rotation={[0, -1.57, 0]}
        scale={[0.73, 0.6, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane061.geometry}
        material={materials["Material.025"]}
        position={[-0.36, 2.63, 3.62]}
        rotation={[0, -1.57, 0]}
        scale={[0.73, 0.6, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane060.geometry}
        material={materials["Material.025"]}
        position={[0.81, 2.63, 3.62]}
        rotation={[0, -1.57, 0]}
        scale={[0.73, 0.6, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane058.geometry}
        material={materials["Material.023"]}
        position={[-0.36, 2.63, 3.62]}
        rotation={[0, -1.57, 0]}
        scale={[0.73, 0.6, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane057.geometry}
        material={materials["Material.023"]}
        position={[0.81, 2.63, 3.62]}
        rotation={[0, -1.57, 0]}
        scale={[0.73, 0.6, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane056.geometry}
        material={materials["Material.020"]}
        position={[-0.66, 2.64, 3.9]}
        rotation={[-1.57, -1.55, -1.57]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane055.geometry}
        material={materials["Material.020"]}
        position={[-0.66, 2.63, 3.9]}
        rotation={[-1.57, -1.55, 1.57]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane054.geometry}
        material={materials["Material.019"]}
        position={[-0.66, 2.64, 3.9]}
        rotation={[-1.57, -1.55, -1.57]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane053.geometry}
        material={materials["Material.019"]}
        position={[-0.66, 2.63, 3.9]}
        rotation={[-1.57, -1.55, 1.57]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane052.geometry}
        material={materials["Material.020"]}
        position={[-0.66, 2.69, 4.06]}
        rotation={[-0.02, -0.85, 3.1]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane051.geometry}
        material={materials["Material.020"]}
        position={[-0.66, 2.63, 4.06]}
        rotation={[-0.02, -0.85, 3.1]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane050.geometry}
        material={materials["Material.020"]}
        position={[-0.66, 2.64, 4.06]}
        rotation={[-0.02, -0.85, -0.04]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane049.geometry}
        material={materials["Material.019"]}
        position={[-0.66, 2.63, 4.06]}
        rotation={[-0.02, -0.85, 3.1]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane048.geometry}
        material={materials["Material.019"]}
        position={[-0.66, 2.64, 4.06]}
        rotation={[-0.02, -0.85, -0.04]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere009.geometry}
        material={materials["Material.020"]}
        position={[-0.51, 2.64, 3.91]}
        rotation={[0, -1.57, 0]}
        scale={-0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere008.geometry}
        material={materials["Material.020"]}
        position={[-0.53, 2.64, 3.87]}
        rotation={[0, -1.57, 0]}
        scale={-0.01}
      />
    </group>
  );
}

useGLTF.preload("/Villa_3.gltf");


